service: tibrahim-pelago-reddit

provider:
  name: aws
  runtime: python3.8

  # you can overwrite defaults here
  stage: ${opt:stage}
  region: ap-southeast-1

  environment: ${file(./env.${opt:stage}.json)}
  profile: ${opt:profile, 'serverless'} # The default profile to use with this service
  memorySize: 256 # Overwrite the default memory size. Default is 1024
  timeout: ${file(./env.${opt:stage}.json):AWS_LAMBDA_EXECUTION_TIMEOUT} # The default is 6 seconds. Note: API Gateway current maximum is 30 seconds
  logRetentionInDays: 14 # Set the default RetentionInDays for a CloudWatch LogGroup
  deploymentBucket: ${file(./env.${opt:stage}.json):AWS_S3_DEPLOYMENT_BUCKET}
  iam:
    role: ${file(./env.${opt:stage}.json):AWS_LAMBDA_EXECUTION_ROLE}
  lambdaHashingVersion: 20201221

# Python and other things
custom:
  pythonRequirements:
    dockerizePip: non-linux
    slim: true

plugins:
  - serverless-python-requirements

# you can add packaging information here
package:
  include:
    - ./pelago_reddit/**
  exclude:
    - '**'

# you can put your functions here
functions:
  topNHotPostIngestion:
    handler: pelago_reddit/topNHotPostIngestion.main
    events:
      - schedule:
          rate: cron(0 * * * ? *)
          enabled: true
    environment: # Function level environment variables
      SERVICE: ${self:service.name}-${opt:stage}-topNHotPostIngestion
    package: {}
